import Lean2dYangMills.SU2FiniteCellulation

/-!
# Kernel dependency audit for the exact SU(2) Migdal closure

This module is imported by the public root so that a clean CI build prints the
kernel dependencies of every principal endpoint in the closure chain.
-/

namespace Lean2dYangMills

#print axioms su2FirstRailMoment_recurrence
#print axioms su2FirstRailMoment_eq
#print axioms su2FirstRailMassMeasure_eq_uniform
#print axioms intervalIntegral_chebyshevU_product_formula
#print axioms integral_su2FirstEntryMass_eq_unitInterval
#print axioms integral_su2Haar_orbit_character_general
#print axioms integral_su2CharacterReal_mul_translate
#print axioms su2CharacterChebyshev_convolution
#print axioms su2HeatKernelPartial_convolution
#print axioms su2HeatKernel_convolution
#print axioms su2Migdal_twoFace_merge
#print axioms su2Migdal_subdivision_invariant
#print axioms su2_exact_simpleLoop_areaLaw
#print axioms SU2PlanarFaceTree.internalEdgeCount_eq_faceCount_sub_one
#print axioms su2PlanarCellulationAmplitude_eq_heatKernel
#print axioms su2PlanarCellulationAmplitude_eq_effectiveFace
#print axioms su2TreePlanar_wilsonExpectation_eq_casimir
#print axioms su2TreePlanarExactAreaLawPackage
#print axioms su2TreePlanar_simpleLoop_areaLaw_exact
#print axioms integral_su2PlanarCellulationAmplitude_eq_one
#print axioms SU2FaceEliminationSchedule.exists_schedule_of_connected_graph
#print axioms SU2FaceEliminationSchedule.exists_valid_schedule_of_dual_connected
#print axioms SU2FaceEliminationSchedule.amplitude_eq_of_valid_schedules
#print axioms SU2ConnectedDiskCellulation.amplitude_eq_heatKernel
#print axioms SU2ConnectedDiskCellulation.amplitude_eq_any_valid_schedule
#print axioms su2ConnectedDisk_wilsonExpectation_eq_casimir
#print axioms su2ConnectedDiskExactAreaLawPackage
#print axioms su2ConnectedDisk_simpleLoop_areaLaw_exact
#print axioms integral_su2ConnectedDiskAmplitude_eq_one

end Lean2dYangMills
