import Lean2dYangMills.SU2BoundaryConditionedGaugeFixing
import Lean2dYangMills.SU2CyclicEdgeElimination
import Lean2dYangMills.SU2PhysicalBoundaryElimination
import Lean2dYangMills.SU2CyclicWordSplicing
import Lean2dYangMills.SU2PhysicalEliminationSchedule
import Lean2dYangMills.SU2PhysicalEliminationIntegral
import Lean2dYangMills.SU2PhysicalBlockInvariant

/-!
# Kernel dependency audit for the exact SU(2) Migdal closure

This module is imported by the public root so that a clean CI build prints the
kernel dependencies of every principal endpoint in the closure chain.
-/

namespace Lean2dYangMills

#print axioms su2FirstRailMoment_recurrence
#print axioms su2FirstRailMoment_eq
#print axioms su2FirstRailMassMeasure_eq_uniform
#print axioms intervalIntegral_chebyshevU_product_formula
#print axioms integral_su2FirstEntryMass_eq_unitInterval
#print axioms integral_su2Haar_orbit_character_general
#print axioms integral_su2CharacterReal_mul_translate
#print axioms su2CharacterChebyshev_convolution
#print axioms su2HeatKernelPartial_convolution
#print axioms su2HeatKernel_convolution
#print axioms su2Migdal_twoFace_merge
#print axioms su2Migdal_subdivision_invariant
#print axioms su2_exact_simpleLoop_areaLaw
#print axioms SU2PlanarFaceTree.internalEdgeCount_eq_faceCount_sub_one
#print axioms su2PlanarCellulationAmplitude_eq_heatKernel
#print axioms su2PlanarCellulationAmplitude_eq_effectiveFace
#print axioms su2TreePlanar_wilsonExpectation_eq_casimir
#print axioms su2TreePlanarExactAreaLawPackage
#print axioms su2TreePlanar_simpleLoop_areaLaw_exact
#print axioms integral_su2PlanarCellulationAmplitude_eq_one
#print axioms SU2FaceEliminationSchedule.exists_schedule_of_connected_graph
#print axioms SU2FaceEliminationSchedule.exists_valid_schedule_of_dual_connected
#print axioms SU2FaceEliminationSchedule.amplitude_eq_of_valid_schedules
#print axioms SU2ConnectedDiskCellulation.amplitude_eq_heatKernel
#print axioms SU2ConnectedDiskCellulation.amplitude_eq_any_valid_schedule
#print axioms su2ConnectedDisk_wilsonExpectation_eq_casimir
#print axioms su2ConnectedDiskExactAreaLawPackage
#print axioms su2ConnectedDisk_simpleLoop_areaLaw_exact
#print axioms integral_su2ConnectedDiskAmplitude_eq_one
#print axioms su2ThreeSpokeGaugeFix_measurePreserving
#print axioms su2ThreeSpoke_density_gaugeFactorization
#print axioms su2ThreeSpoke_gaugeFixedIntegral_eq_heatKernel
#print axioms su2ThreeSpoke_unreducedIntegral_eq_gaugeFixedIntegral
#print axioms su2ThreeSpoke_unreducedIntegral_eq_heatKernel
#print axioms su2Migdal_eliminate_cyclic_pos_neg
#print axioms su2Migdal_eliminate_cyclic_neg_pos
#print axioms SU2FiniteDiskCellulation.evalDartWord_dartWord
#print axioms SU2EdgeConnectedDiskCellulation.exists_cyclicFaceMerge_of_dualAdj
#print axioms SU2EdgeConnectedDiskCellulation.CyclicFaceMerge.integrate_selected_edge
#print axioms su2FiniteStarDiagonalLeft_measurePreserving
#print axioms su2FiniteStarGaugeFix_measurePreserving
#print axioms su2FiniteStar_integral_eq_gaugeFixed
#print axioms su2FiniteStar_integral_eq_identitySlice
#print axioms SU2RootedTreeOrder.exists_validForGraph_of_connected
#print axioms SU2RootedTreeOrder.coordinateEquiv_measurePreserving
#print axioms SU2FiniteDiskCellulation.exists_rootedSpanningTree_of_primal_connected
#print axioms SU2FiniteDiskCellulation.RootedSpanningTree.vertexCoordinateEquiv_measurePreserving
#print axioms SU2FiniteDiskCellulation.exists_rootedTreeVertexCoordinateEquiv_measurePreserving
#print axioms SU2RootedTreeOrder.parentIndex_lt_child
#print axioms SU2FiniteDiskCellulation.RootedSpanningTree.treeEdge_injective
#print axioms SU2FiniteDiskCellulation.RootedSpanningTree.globalEdgeGaugeEquiv_measurePreserving
#print axioms SU2FiniteDiskCellulation.RootedSpanningTree.gaugeTransform_eq_gaugeFixedEdgeConfiguration
#print axioms SU2FiniteDiskCellulation.dartHolonomy_gaugeTransform_of_closed
#print axioms SU2EdgeConnectedDiskCellulation.allFaceHolonomies_gaugeTransform
#print axioms SU2EdgeConnectedDiskCellulation.exists_globalEdgeGaugeEquiv_measurePreserving
#print axioms SU2EdgeConnectedDiskCellulation.edgeHeatKernelDensity_globalEdgeFactorization
#print axioms SU2EdgeConnectedDiskCellulation.unreducedEdgeIntegral_eq_chordGaugeFixedIntegral
#print axioms SU2BoundaryDiskCellulation.BoundaryGaugeChart.card_chordEdge_eq_card_face
#print axioms SU2BoundaryDiskCellulation.BoundaryGaugeChart.chordBoundaryEquiv_measurePreserving
#print axioms SU2BoundaryDiskCellulation.BoundaryGaugeChart.conditionedEdgeIntegral_eq_conditionedChordIntegral
#print axioms SU2BoundaryDiskCellulation.BoundaryGaugeChart.globalBoundaryEdgeEquiv_measurePreserving
#print axioms SU2BoundaryDiskCellulation.BoundaryGaugeChart.globalBoundaryEdgeEquiv_apply_exterior
#print axioms SU2BoundaryDiskCellulation.BoundaryGaugeChart.unreducedEdgeIntegral_eq_integral_conditionedEdgeIntegral
#print axioms SU2FiniteDiskCellulation.dartHolonomy_add
#print axioms SU2BoundaryDiskCellulation.exists_exterior_edge_not_tree
#print axioms SU2BoundaryDiskCellulation.nonempty_adaptiveBoundaryGaugeChart
#print axioms SU2BoundaryDiskCellulation.AdaptiveBoundaryGaugeChart.conditionedEdgeIntegral_eq_conditionedChordIntegral
#print axioms SU2BoundaryDiskCellulation.AdaptiveBoundaryGaugeChart.globalPhysicalBoundaryEdgeEquiv_measurePreserving
#print axioms SU2BoundaryDiskCellulation.AdaptiveBoundaryGaugeChart.globalPhysicalBoundaryEdgeEquiv_apply_exterior
#print axioms SU2EdgeConnectedDiskCellulation.nonempty_dualRootedEliminationTree
#print axioms SU2DualRootedEliminationTree.selectedEdge_injective
#print axioms SU2DualRootedEliminationTree.card_selectedEdgeRange
#print axioms SU2DualRootedEliminationTree.selectedEdge_ne_exteriorEdge
#print axioms SU2PhysicalBoundaryEliminationChart.stepChord_bijective
#print axioms SU2PhysicalBoundaryEliminationChart.stepChordEquiv
#print axioms SU2PhysicalBoundaryEliminationChart.internalCoordinateEquiv_measurePreserving
#print axioms SU2BoundaryDiskCellulation.AdaptiveBoundaryGaugeChart.nonempty_physicalBoundaryEliminationChart_of_connected
#print axioms SU2FiniteDiskCellulation.CyclicDartWordMerge.eval_mergedWord
#print axioms SU2FiniteDiskCellulation.CyclicDartWordMerge.ofMem
#print axioms SU2FiniteDiskCellulation.CyclicDartWordMerge.mem_spliceAt_iff_of_edge_ne
#print axioms SU2FiniteDiskCellulation.CyclicDartWordMerge.mem_mergedWord_iff_of_edge_ne
#print axioms SU2FiniteDiskCellulation.CyclicDartWordMerge.mergedWord_avoids_selectedEdge
#print axioms SU2EdgeConnectedDiskCellulation.CyclicFaceMerge.mergedWord_avoids_selectedEdge
#print axioms SU2RootedTreeOrder.leafList_constructionSchedule
#print axioms SU2RootedTreeOrder.constructionSchedule_locallyValidGraph
#print axioms SU2DualRootedEliminationTree.physicalSchedule_valid
#print axioms SU2DualRootedEliminationTree.physicalSchedule_amplitude_eq_heatKernel_totalArea
#print axioms su2SplitLastEquiv_measurePreserving
#print axioms su2FiniteProductHaar_integral_splitLast
#print axioms su2SplitLastRestFirstEquiv_measurePreserving
#print axioms su2FiniteProductHaar_integral_iteratedLast
#print axioms SU2PhysicalBoundaryEliminationChart.conditionedChordIntegral_eq_indexedIntegral
#print axioms SU2FiniteDiskCellulation.RootedSpanningTree.continuous_gaugeFixedEdgeConfiguration
#print axioms SU2BoundaryDiskCellulation.AdaptiveBoundaryGaugeChart.continuous_chordWithAnchorOne
#print axioms SU2BoundaryDiskCellulation.AdaptiveBoundaryGaugeChart.continuous_chordExteriorPrefix
#print axioms SU2BoundaryDiskCellulation.AdaptiveBoundaryGaugeChart.continuous_chordExteriorSuffix
#print axioms SU2BoundaryDiskCellulation.AdaptiveBoundaryGaugeChart.continuous_chordBoundaryEquiv_symm_const
#print axioms SU2PhysicalBoundaryEliminationChart.continuous_conditionedChordDensity
#print axioms SU2PhysicalBoundaryEliminationChart.integrable_conditionedChordDensity
#print axioms SU2PhysicalBoundaryEliminationChart.integrable_indexedConditionedChordDensity
#print axioms SU2PhysicalBoundaryEliminationChart.internalCoordinateEquiv_symm_apply_stepChord
#print axioms SU2PhysicalBoundaryEliminationChart.chordBoundaryEquiv_symm_apply_other
#print axioms SU2PhysicalBoundaryEliminationChart.conditionedGaugeFixed_selectedEdge
#print axioms SU2FiniteDiskCellulation.CyclicDartWordMerge.wordCompleteAwayFrom_spliceAt
#print axioms SU2FiniteDiskCellulation.CyclicDartWordMerge.wordSound_spliceAt

end Lean2dYangMills
