import Lean2dYangMills.SU2HeatSemigroup
import Lean2dYangMills.SU2ExactAreaLaw
import Lean2dYangMills.Interfaces

/-!
# Global reduction for tree-dual planar disk cellulations

A `SU2PlanarFaceTree` is a finite planar disk cellulation obtained by starting
from positive-area faces and repeatedly gluing two disks along one oppositely
oriented boundary edge.  Its dual graph is a tree.  The recursive amplitude
contains one actual normalized Haar integral for every internal edge.

The main theorem eliminates all those edges and replaces the cellulation by a
single heat-kernel face whose area is the sum of the original face areas.  The
result is then consumed by a nontrivial `ExactAreaLawPackage` instance for each
SU(2) representation label.

This module does not claim the corresponding reduction for arbitrary planar
cellulations with cycles in the dual graph.
-/

noncomputable section

namespace Lean2dYangMills

open MeasureTheory

/-- Finite positive-area disk cellulations generated by binary planar gluing.
Every `glue` constructor records one internal edge with opposite orientations
in the two child boundary words. -/
inductive SU2PlanarFaceTree where
  | face (area : Real) (area_pos : 0 < area)
  | glue (left right : SU2PlanarFaceTree)

namespace SU2PlanarFaceTree

/-- Total geometric area of all faces. -/
def totalArea : SU2PlanarFaceTree -> Real
  | .face area _ => area
  | .glue left right => left.totalArea + right.totalArea

/-- Number of elementary faces. -/
def faceCount : SU2PlanarFaceTree -> Nat
  | .face _ _ => 1
  | .glue left right => left.faceCount + right.faceCount

/-- Number of Haar-integrated internal edges in the recursive presentation. -/
def internalEdgeCount : SU2PlanarFaceTree -> Nat
  | .face _ _ => 0
  | .glue left right => left.internalEdgeCount + right.internalEdgeCount + 1

theorem totalArea_pos (C : SU2PlanarFaceTree) : 0 < C.totalArea := by
  induction C with
  | face area harea => simpa [totalArea] using harea
  | glue left right hleft hright =>
      simpa [totalArea] using add_pos hleft hright

theorem faceCount_pos (C : SU2PlanarFaceTree) : 0 < C.faceCount := by
  induction C with
  | face => simp [faceCount]
  | glue left right hleft hright =>
      simp only [faceCount]
      omega

/-- A tree-dual cellulation with `F` faces has exactly `F - 1` internal edges.
This is the numerical termination certificate for recursive edge elimination. -/
theorem internalEdgeCount_eq_faceCount_sub_one (C : SU2PlanarFaceTree) :
    C.internalEdgeCount = C.faceCount - 1 := by
  induction C with
  | face => simp [internalEdgeCount, faceCount]
  | glue left right hleft hright =>
      have hlpos := faceCount_pos left
      have hrpos := faceCount_pos right
      simp only [internalEdgeCount, faceCount]
      rw [hleft, hright]
      omega

/-- Collapse a finite tree-dual cellulation to its one effective face. -/
def effectiveFace (C : SU2PlanarFaceTree) : SU2PlanarFaceTree :=
  .face C.totalArea C.totalArea_pos

@[simp] theorem totalArea_effectiveFace (C : SU2PlanarFaceTree) :
    C.effectiveFace.totalArea = C.totalArea := rfl

@[simp] theorem faceCount_effectiveFace (C : SU2PlanarFaceTree) :
    C.effectiveFace.faceCount = 1 := rfl

@[simp] theorem internalEdgeCount_effectiveFace (C : SU2PlanarFaceTree) :
    C.effectiveFace.internalEdgeCount = 0 := rfl

end SU2PlanarFaceTree

/-- Recursive lattice density with one real Haar integration for each internal
edge.  At a gluing node, `x` occurs with opposite orientations in the two face
blocks, exactly as in the concrete two-face Migdal theorem. -/
def su2PlanarCellulationAmplitude : SU2PlanarFaceTree -> SU2 -> SU2 -> Complex
  | .face area _ => fun a b => su2HeatKernel area (a * b)
  | .glue left right => fun a b =>
      ∫ x : SU2,
        su2PlanarCellulationAmplitude left a x *
          su2PlanarCellulationAmplitude right x⁻¹ b ∂su2HaarProb

/-- Iterated internal-edge elimination: every finite tree-dual cellulation is
exactly one effective heat-kernel face. -/
theorem su2PlanarCellulationAmplitude_eq_heatKernel
    (C : SU2PlanarFaceTree) (a b : SU2) :
    su2PlanarCellulationAmplitude C a b =
      su2HeatKernel C.totalArea (a * b) := by
  induction C generalizing a b with
  | face area harea => rfl
  | glue left right hleft hright =>
      simp only [su2PlanarCellulationAmplitude]
      simp_rw [hleft, hright]
      simpa [SU2PlanarFaceTree.totalArea] using
        su2Migdal_subdivision_invariant
          (SU2PlanarFaceTree.totalArea_pos left)
          (SU2PlanarFaceTree.totalArea_pos right) a b

/-- Consumer theorem: the recursively integrated cellulation equals its
explicit one-face collapse, with no package field. -/
theorem su2PlanarCellulationAmplitude_eq_effectiveFace
    (C : SU2PlanarFaceTree) (a b : SU2) :
    su2PlanarCellulationAmplitude C a b =
      su2PlanarCellulationAmplitude C.effectiveFace a b := by
  rw [su2PlanarCellulationAmplitude_eq_heatKernel]
  rfl

/-- The fixed-label simple-loop theory whose loop data are finite tree-dual
cellulations and whose expectation is the Wilson character integrated against
the full recursively glued lattice density. -/
def su2TreePlanarSimpleLoopTheory (n : Nat) : PlaneSimpleLoopTheory where
  Loop := SU2PlanarFaceTree
  area := SU2PlanarFaceTree.totalArea
  wilsonExpectation := fun C =>
    ∫ g : SU2,
      su2NormalizedWilsonCharacter n g *
        su2PlanarCellulationAmplitude C 1 g ∂su2HaarProb
  stringTension := ((n : Real) * ((n : Real) + 2)) / 4

/-- Exact coefficient after all internal edges of a finite tree-dual planar
cellulation have been eliminated. -/
theorem su2TreePlanar_wilsonExpectation_eq_casimir
    (n : Nat) (C : SU2PlanarFaceTree) :
    (su2TreePlanarSimpleLoopTheory n).wilsonExpectation C =
      ((Real.exp (-C.totalArea *
        (((n : Real) * ((n : Real) + 2)) / 4)) : Real) : Complex) := by
  change (∫ g : SU2,
      su2NormalizedWilsonCharacter n g *
        su2PlanarCellulationAmplitude C 1 g ∂su2HaarProb) = _
  simp_rw [su2PlanarCellulationAmplitude_eq_heatKernel]
  simp only [one_mul, su2HeatKernel]
  exact su2_exact_simpleLoop_areaLaw C.totalArea_pos n

/-- A nontrivial concrete `ExactAreaLawPackage` for every SU(2) label and every
finite tree-dual positive-area planar disk cellulation. -/
def su2TreePlanarExactAreaLawPackage (n : Nat) :
    ExactAreaLawPackage (su2TreePlanarSimpleLoopTheory n) where
  area_nonnegative := fun C => C.totalArea_pos.le
  stringTension_nonnegative := by
    exact div_nonneg
      (mul_nonneg (Nat.cast_nonneg n) (by positivity)) (by norm_num)
  wilson_eq_areaLaw := by
    intro C
    rw [su2TreePlanar_wilsonExpectation_eq_casimir]
    rw [areaLawValue]
    change ((Real.exp (-C.totalArea *
      (((n : Real) * ((n : Real) + 2)) / 4)) : Real) : Complex) =
        Complex.exp (((-(((n : Real) * ((n : Real) + 2)) / 4) *
          C.totalArea : Real) : Complex))
    rw [← Complex.ofReal_exp]
    congr 2
    ring

/-- Public package consumer: the generic exact-area-law API now evaluates a
nontrivial concrete two-dimensional SU(2) planar cellulation. -/
theorem su2TreePlanar_simpleLoop_areaLaw_exact
    (n : Nat) (C : SU2PlanarFaceTree) :
    (su2TreePlanarSimpleLoopTheory n).wilsonExpectation C =
      areaLawValue (su2TreePlanarSimpleLoopTheory n) C :=
  simpleLoop_areaLaw_exact (su2TreePlanarExactAreaLawPackage n) C

/-- Normalization of the recursively reduced heat-kernel functional.  This is
the trivial-representation (`n = 0`) consumer of the exact area-law theorem. -/
theorem integral_su2PlanarCellulationAmplitude_eq_one
    (C : SU2PlanarFaceTree) :
    (∫ g : SU2, su2PlanarCellulationAmplitude C 1 g ∂su2HaarProb) = 1 := by
  have h := su2TreePlanar_wilsonExpectation_eq_casimir 0 C
  simpa [su2TreePlanarSimpleLoopTheory, su2NormalizedWilsonCharacter,
    su2CharacterChebyshev, Polynomial.Chebyshev.U_zero] using h

end Lean2dYangMills
