import Lean2dYangMills.SU2PhysicalBoundaryElimination
import Lean2dYangMills.SU2CyclicWordSplicing

/-!
# The abstract schedule carried by a physical elimination tree

A construction-ordered rooted tree canonically yields a binary schedule:
at each growth step the previous block is merged with the newly attached
face.  This module proves that the schedule lists every face exactly once and
is valid for the independently defined dual graph.  It therefore identifies
the abstract schedule consumed by the exact amplitude with the same physical
parent--child adjacencies used for edge elimination.
-/

noncomputable section

namespace Lean2dYangMills

namespace SU2RootedTreeOrder

/-- Binary face schedule obtained by replaying the leaf-attachment order. -/
def constructionSchedule {F : Type} : {n : Nat} ->
    SU2RootedTreeOrder n -> (Fin (n + 1) -> F) ->
      SU2FaceEliminationSchedule F
  | 0, .root, label => .leaf (label 0)
  | n + 1, .grow tree _, label =>
      .merge
        (tree.constructionSchedule (fun i => label (Fin.castSucc i)))
        (.leaf (label (Fin.last (n + 1))))

/-- The schedule leaf list is literally the construction-order list. -/
theorem leafList_constructionSchedule {F : Type} : {n : Nat} ->
    (tree : SU2RootedTreeOrder n) -> (label : Fin (n + 1) -> F) ->
      (tree.constructionSchedule label).leafList = List.ofFn label
  | 0, .root, label => by
      simp [constructionSchedule, SU2FaceEliminationSchedule.leafList]
  | n + 1, .grow tree parent, label => by
      rw [constructionSchedule, SU2FaceEliminationSchedule.leafList,
        leafList_constructionSchedule]
      simpa using (List.ofFn_succ' label).symm

/-- Parent adjacency at every non-root construction vertex is sufficient for
local validity of the induced binary schedule. -/
theorem constructionSchedule_locallyValidGraph {F : Type}
    (G : SimpleGraph F) : {n : Nat} ->
    (tree : SU2RootedTreeOrder n) -> (label : Fin (n + 1) -> F) ->
    (∀ i : Fin n,
      G.Adj (label (tree.parentIndex i)) (label (Fin.succ i))) ->
      (tree.constructionSchedule label).locallyValidGraph G
  | 0, .root, label, _ => trivial
  | n + 1, .grow tree parent, label, hadj => by
      let oldLabel : Fin (n + 1) -> F :=
        fun i => label (Fin.castSucc i)
      have holdAdj : ∀ i : Fin n,
          G.Adj (oldLabel (tree.parentIndex i))
            (oldLabel (Fin.succ i)) := by
        intro i
        have hi := hadj (Fin.castSucc i)
        simpa [oldLabel, parentIndex] using hi
      have hold := constructionSchedule_locallyValidGraph G tree oldLabel holdAdj
      have hlast := hadj (Fin.last n)
      have hparentMem : label (Fin.castSucc parent) ∈
          (tree.constructionSchedule oldLabel).leafList := by
        rw [leafList_constructionSchedule]
        rw [List.mem_ofFn]
        exact ⟨parent, rfl⟩
      refine ⟨hold, trivial,
        label (Fin.castSucc parent), hparentMem,
        label (Fin.last (n + 1)), ?_, ?_⟩
      · simp [SU2FaceEliminationSchedule.leafList]
      · simpa [parentIndex] using hlast

end SU2RootedTreeOrder

namespace SU2DualRootedEliminationTree

variable {P : SU2EdgeConnectedDiskCellulation}
  (T : SU2DualRootedEliminationTree P)

/-- The binary abstract schedule induced by the physical dual tree. -/
def physicalSchedule :
    SU2FaceEliminationSchedule P.connected.cellulation.Face :=
  T.order.constructionSchedule T.faceOrder

theorem physicalSchedule_leafList :
    T.physicalSchedule.leafList = List.ofFn T.faceOrder := by
  exact T.order.leafList_constructionSchedule T.faceOrder

theorem physicalSchedule_locallyValid :
    T.physicalSchedule.locallyValid P.connected.cellulation := by
  apply T.order.constructionSchedule_locallyValidGraph
  exact T.parent_adj

/-- **Physical/abstract schedule compatibility.**  The schedule generated by
the physical elimination tree is valid for the independent cellulation: it
crosses genuine dual adjacencies and enumerates every bounded face once. -/
theorem physicalSchedule_valid :
    T.physicalSchedule.ValidFor P.connected.cellulation := by
  refine ⟨T.physicalSchedule_locallyValid, ?_⟩
  have hnodup : T.physicalSchedule.leafList.Nodup := by
    rw [T.physicalSchedule_leafList, List.nodup_ofFn]
    exact T.faceOrder.injective
  apply (List.perm_ext_iff_of_nodup hnodup
    (Finset.nodup_toList
      (Finset.univ : Finset P.connected.cellulation.Face))).2
  intro f
  rw [T.physicalSchedule_leafList]
  simp only [List.mem_ofFn, Finset.mem_toList, Finset.mem_univ, iff_true]
  exact T.faceOrder.surjective f

/-- Consequently the schedule carried by the physical tree evaluates to the
already formalized exact heat kernel at total area. -/
theorem physicalSchedule_amplitude_eq_heatKernel_totalArea (a b : SU2) :
    T.physicalSchedule.amplitude P.connected.cellulation a b =
      su2HeatKernel P.connected.cellulation.totalArea (a * b) := by
  exact SU2FaceEliminationSchedule.amplitude_eq_heatKernel_totalArea
    P.connected.cellulation T.physicalSchedule T.physicalSchedule_valid a b

end SU2DualRootedEliminationTree

end Lean2dYangMills
